### ISSUE TITLE
Problem migrating to full system logging

### ISSUE THREAD

**Issue by guapuruvu** [civicrm/org.civicrm.civicase#104]
Hi, installation worked but I'm unable to enable full system logging. I tried clicking "Yes" for Logging under civicrm/admin/setting/misc?reset=1, and also by running this command "cv api setting.create logging=1". In both cases, I get:

{
    "error_code": "unknown error",
    "tip": "add debug=1 to your API call to have more info about the error",
    "is_error": 1,
    "error_message": "DB Error: unknown error"
}

I can send the debug info if that would be helpful. Is this something you can help with, or should I ask someone else?

**Comment by colemanw** [comment]
That's not directly related to this extension. Might be best for you to discuss on chat.civicrm.org to see if you can get more clarity about what's causing the error.

**Comment by guapuruvu** [comment]
Thanks. I'm giving that a try. So far no luck.
