### ISSUE TITLE
Inactive case types not filtered out on dashboard

### ISSUE THREAD

**Issue by aydun** [civicrm/org.civicrm.civicase#106]
Case Types that are disabled still show in the Dashboard summary and Open/Closed stats.
For Case Summary, the 'breakdown by type' is not shown if there is only 1 enabled type, but the ongoing/resolved/urgent stats are for all types.

**Comment by colemanw** [comment]
Thanks for filing this @aydun - do you have a moment to test the patch?

**Comment by aydun** [comment]
Tested = that fixes the problems I was seeing.
