### ISSUE TITLE
Civicrm 5.6.1 - "CiviCase: access all cases and activities" permission issue

### ISSUE THREAD

**Issue by Myrddinwylit** [civicrm/org.civicrm.civicase#120]
Civicrm 5.6.1 - "CiviCase: access all cases and activities" permission issue- I originally posted this issue [Here](https://civicrm.stackexchange.com/questions/27218/civicase-access-all-cases-and-activities-issues)

There is an issue somewhere in this extension that when you do not enable "access all cases and activities" for a user (which we dont want to do) if the user goes to the Case Dashboard or Case Management  you get a "ERR_TOO_MANY_REDIRECTS" - when the extension is disabled the system works as it is suppose to.

**Comment by yashodha** [comment]
@Myrddinwylit 

Can you check https://github.com/civicrm/org.civicrm.civicase/pull/123 for the same

**Comment by yashodha** [comment]
@Myrddinwylit @colemanw  does the patch help? If yes, this could be merged.
