### ISSUE TITLE
Double browser history when visiting a url with crmRouteBinder defaults

### ISSUE THREAD

**Issue by colemanw** [civicrm/org.civicrm.civicase#39]
When following a link to an angular page using crmRouteBinder, the defaults get injected into the URL immediately on page load, which results in a double-entry in the browser history so the back button doesn't work correctly.

2 solutions come to mind:

1. Push the params to the url while somehow avoiding an entry in the browser history, which [this suggests](https://stackoverflow.com/a/19016166/2918050) is a possiblility.
2. Do not push defaults into the url. Only update the url when the value changes from the default. I personally like this option because it keeps the url bar cleaner.

**Comment by totten** [comment]
This came up before while adding the new screens to the Civi menu. I used a quick/simple work-around -- just pass all the args explicitly. 🙄  It looks like that's been [removed](https://github.com/civicrm/org.civicrm.civicase/commit/acf188d79f7103216f4a0b4dc61a2ae02069e528), though.

The other two approaches sound more maintainable, of course. Both seem fine. 

Comparing those two on usability/functionality grounds... we could concoct some edge-cases where a user bookmarks a screen, and then the application changes to new defaults, and then it becomes arguable whether the bookmark should've had a fully-specified filter-set (`#1`) or partially-specified filter-set (`#2`). It's probably 50/50 on each approach capturing the user's intent, so IMHO that's a wash.

Better to go with whatever solution is shippable sooner. I'll fiddle with it a bit and see about implementing one or the other.
