### ISSUE TITLE
Problems on Windows Systems when Accessing Templates

### ISSUE THREAD

**Issue by MiyaNoctem** [civicrm/org.civicrm.civicase#92]
On path *templates/CRM/* there are two directories, one called 'civicase', while the second one is called 'Civicase' (note the only difference between the two is the upper case 'C'). This causes problems on Windows systems, as it treats them as a single directory, so when you look at the contents of each one, you'll see it has the same, while in reality, their contents differ. I'd suppose the naming of directory 'civicase' with lower case 'c' is a typo, but I'm not 100% sure... so I'm reporting the issue so better men can have a look at it.

**Comment by colemanw** [comment]
The civicase directory contained nothing but an empty, unused file. So I've deleted it.
